workflows:
  isignapp-ios:
    name: ISignApp iOS Build (No Signing)
    environment:
      xcode: latest
      vars:
        APP_SCHEME: "ISignApp"
    scripts:
      - scripts:
  - name: Build (debug, no signing)
    script: |
      xcodebuild clean build -scheme "$APP_SCHEME" -sdk iphonesimulator -configuration Debug
          xcodebuild archive -scheme "$APP_SCHEME" -sdk iphoneos -archivePath $HOME/build/ISignApp.xcarchive
          xcodebuild -exportArchive -archivePath $HOME/build/ISignApp.xcarchive \
            -exportPath $HOME/build/Export \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/Export/*.ipa
