workflows:
  isignapp-ios:
    name: ISignApp iOS Build (No Signing)
    environment:
      xcode: latest
      vars:
        APP_SCHEME: "ISignApp"
    scripts:
      - name: Build .app for Simulator (no signing)
        script: |
          xcodebuild clean build \
            -scheme "$APP_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build/
    artifacts:
      - build/Build/Products/Debug-iphonesimulator/*.app
